arcpy.MakeTableView_management("W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis","tracts_2000_centroid_5km_buf_int_tracts_dis_VIEW","#","#","OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;tractid tractid VISIBLE NONE;origtractarea origtractarea VISIBLE NONE;tractid_1 tractid_1 VISIBLE NONE;origtractarea_1 origtractarea_1 VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE;newtractarea newtractarea VISIBLE NONE;pcttractarea pcttractarea VISIBLE NONE")

arcpy.TableToTable_conversion("W:/GIS/Projects/king_county/data/input/census.gdb/dec_00_sf3_p001","W:/GIS/Projects/king_county/data/processing/tables.gdb","census_2000_sf3_p001","#","""GEO_id "GEO_id" true true false 255 Text 0 0 ,First,#,W:/GIS/Projects/king_county/data/input/census.gdb/dec_00_sf3_p001,GEO_id,-1,-1;GEO_id2 "GEO_id2" true true false 15 Text 0 0 ,First,#,W:/GIS/Projects/king_county/data/input/census.gdb/dec_00_sf3_p001,GEO_id2,-1,-1;GEO_display_label "GEO_display_label" true true false 255 Text 0 0 ,First,#,W:/GIS/Projects/king_county/data/input/census.gdb/dec_00_sf3_p001,GEO_display_label,-1,-1;VD01 "VD01" true true false 4 Long 0 0 ,First,#,W:/GIS/Projects/king_county/data/input/census.gdb/dec_00_sf3_p001,VD01,-1,-1;pop2000 "pop2000" true true false 4 Long 0 0 ,First,#,W:/GIS/Projects/king_county/data/input/census.gdb/dec_00_sf3_p001,pop2000,-1,-1""","#")

arcpy.AddJoin_management("tracts_2000_centroid_5km_buf_int_tracts_dis_VIEW","tractid_1","W:/GIS/Projects/king_county/data/processing/tables.gdb/census_2000_sf3_p001","GEO_id2","KEEP_ALL")

arcpy.TableToTable_conversion("tracts_2000_centroid_5km_buf_int_tracts_dis_VIEW","W:/GIS/Projects/king_county/data/processing/tables.gdb","tracts_2000_centroid_5km_buf_int_tracts_dis_census","#","""tractid "tractid" true true false 15 Text 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,tracts_2000_centroid_5km_buf_int_tracts_dis.tractid,-1,-1;origtractarea "origtractarea" true true false 8 Double 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,tracts_2000_centroid_5km_buf_int_tracts_dis.origtractarea,-1,-1;tractid_1 "tractid" true true false 15 Text 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,tracts_2000_centroid_5km_buf_int_tracts_dis.tractid_1,-1,-1;origtractarea_1 "origtractarea" true true false 8 Double 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,tracts_2000_centroid_5km_buf_int_tracts_dis.origtractarea_1,-1,-1;Shape_Length "Shape_Length" false true true 8 Double 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,tracts_2000_centroid_5km_buf_int_tracts_dis.Shape_Length,-1,-1;Shape_Area "Shape_Area" false true true 8 Double 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,tracts_2000_centroid_5km_buf_int_tracts_dis.Shape_Area,-1,-1;newtractarea "newtractarea" true true false 8 Double 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,tracts_2000_centroid_5km_buf_int_tracts_dis.newtractarea,-1,-1;pcttractarea "pcttractarea" true true false 4 Float 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,tracts_2000_centroid_5km_buf_int_tracts_dis.pcttractarea,-1,-1;census_2000_sf3_p001_GEO_id2 "GEO_id2" true true false 15 Text 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,census_2000_sf3_p001.GEO_id2,-1,-1;census_2000_sf3_p001_VD01 "VD01" true true false 4 Long 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,census_2000_sf3_p001.VD01,-1,-1;pop2000 "pop2000" true true false 4 Long 0 0 ,First,#,W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis,census_2000_sf3_p001.pop2000,-1,-1""","#")

arcpy.AddField_management("W:/GIS/Projects/king_county/data/processing/tables.gdb/tracts_2000_centroid_5km_buf_int_tracts_dis_census","pop2000trtcentroid5kmbuf","FLOAT","#","#","#","#","NULLABLE","NON_REQUIRED","#")

arcpy.CalculateField_management("W:/GIS/Projects/king_county/data/processing/tables.gdb/tracts_2000_centroid_5km_buf_int_tracts_dis_census","pop2000trtcentroid5kmbuf","!pcttractarea! * !pop2000!","PYTHON_9.3","#")

arcpy.Frequency_analysis("W:/GIS/Projects/king_county/data/processing/tables.gdb/tracts_2000_centroid_5km_buf_int_tracts_dis_census","W:/GIS/Projects/king_county/data/processing/tables.gdb/tracts_2000_centroid_5km_buf_population","tractid","pop2000trtcentroid5kmbuf")

arcpy.ImportToolbox('C:\Program Files (x86)\DataEast\XTools Pro\Toolbox\XTOOLS PRO.tbx')
arcpy.XToolsGP_Export2Text("W:/GIS/Projects/king_county/data/processing/tables.gdb/tracts_2000_centroid_5km_buf_population", "FREQUENCY;tractid;pop2000trtcentroid5kmbuf", "W:/GIS/Projects/king_county/data/processing/tables/buffer_census_data/tract_2000_5km_buf_population.txt")
arcpy.XToolsGP_Export2Text("W:/GIS/Projects/king_county/data/processing/tables.gdb/census_2000_sf3_p001"                   , "GEO_id2;pop2000",                            "W:/GIS/Projects/king_county/data/processing/tables/buffer_census_data/tract_2000_population.txt")