arcpy.Erase_analysis("W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000","W:/GIS/Projects/king_county/data/processing/king_county.gdb/king_county_area_water","W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_erase_water_area","#")
arcpy.Dissolve_management("W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_erase_water_area","W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_erase_water_area_dis","STATEFP00;COUNTYFP00;TRACTCE00;CTIDFP00;NAME00;NAMELSAD00;MTFCC00;FUNCSTAT00;ALAND00;AWATER00;INTPTLAT00;INTPTLON00;tractid;origtractarea","#","MULTI_PART","DISSOLVE_LINES")
arcpy.AddField_management("W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_erase_water_area_dis","land_area_sq_meters","DOUBLE","#","#","#","#","NULLABLE","NON_REQUIRED","#")
arcpy.CalculateField_management("W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_erase_water_area_dis","land_area_sq_meters","!shape.area@squaremeters!","PYTHON_9.3","#")

arcpy.Erase_analysis("W:/GIS/Projects/king_county/data/processing/census_tract_centroid_buffers.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis","W:/GIS/Projects/king_county/data/processing/king_county.gdb/king_county_area_water","W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis_er_water","#")
arcpy.Dissolve_management("W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis_er_water","W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis_er_water_dis","tractid","#","MULTI_PART","DISSOLVE_LINES")
arcpy.AddField_management("W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis_er_water_dis","b5km_land_area_sq_meters","DOUBLE","#","#","#","#","NULLABLE","NON_REQUIRED","#")
arcpy.CalculateField_management("W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis_er_water_dis","b5km_land_area_sq_meters","!shape.area@squaremeters!","PYTHON_9.3","#")

arcpy.ImportToolbox('C:\Program Files (x86)\DataEast\XTools Pro\Toolbox\XTOOLS PRO.tbx')
arcpy.XToolsGP_Export2Text("W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_erase_water_area_dis",                        "tractid;origtractarea;land_area_sq_meters","W:/GIS/Projects/king_county/data/processing/tables/tract_2000_land_area.txt","false","false")
arcpy.XToolsGP_Export2Text("W:/GIS/Projects/king_county/data/processing/tract_land_area_water.gdb/utm_z10n/tracts_2000_centroid_5km_buf_int_tracts_dis_er_water_dis","tractid;b5km_land_area_sq_meters",         "W:/GIS/Projects/king_county/data/processing/tables/tract_centroid_b5km_land_area.txt","false","false")